### PR TITLE
Add Travis build status

### PR DESCRIPTION
**Pull request by oliv3**
Hi,
Just replace with your Travis credentials where needed, and you should be fine

### CODE REVIEW

**Comment by ltratt** [comment]
This looks mostly good, except the README and README.md have got muddled up somehow? I don't think we should have README.md, so I'd prefer to just put a simple link into the README.

**Comment by oliv3** [comment]
Github requires a markdown README hence the link to the original README, so the link is already included in the README, but feel free to change that

The really important thing is to have a .travis.yml with your setup, so Travis will be triggered when a push is made

**Comment by ltratt** [comment]
I've sort-of merged a variant of this in. I might have got it wrong, so please feel free to correct me if I have!

**Comment by oliv3** [comment]
On 05/25/2015 05:17 PM, Laurence Tratt wrote:
> I've sort-of merged a variant of this in. I might have got it wrong, so
> please feel free to correct me if I have!

Hi, I was giving a quick look at it right now since you closed the PR;
seems ok, will check deeper tonight

Best,

--
Olivier

**Pull request closed without merging**
