### PR TITLE
Explicitly check for bison/yacc and use appropriately if found.

### PR DESCRIPTION
**Pull request by ltratt**
Previously we searched for flex/lex but always used lex, but that could cause errors on systems like Travis, which seem to have slightly broken versions of lex lying around.

This commit homogenises this: we now use the standard autoconf macros for finding lex/yacc and use whatever program they find.

### CODE REVIEW

**Comment by ltratt** [comment]
@oliv3 `-Werror` turns out to be too much for Travis, so I think we have to remove that (and `-pedantic-error` too). If you're OK with this, I suggest I squash those last two commits before merging.

**Comment by oliv3** [comment]
Squash the three you mean ?

**Comment by ltratt** [comment]
Just the last two (if you're OK with it) and then force pushing.

**Comment by ltratt** [comment]
I wanted to squash this before you merged :( I'm going to back things out of master and reraise.

**Comment by oliv3** [comment]
Ok so this was "fixup last two commits then squash everything", sorry...

**Comment by ltratt** [comment]
Ah, no, I see you squashed things. OK, that wasn't what I expected, but that's my fault for not being clear! I think it's the PR proposer's job to do the squashing and then the reviewer's job to check it's done properly. In this case it would have made your life easier :)

Anyway, no harm done, and no need to reraise anything.

**Pull request merged**
