### PR TITLE
Don't try and write a child process's stderr if there's nothing there.

### LINKED ISSUE #37: Error messages are not displayed when using -m batch
Looks like there's an issue here:

https://github.com/ltratt/extsmail/blob/master/extsmaild.c#L1210-L1212

When running `extsmaild -m batch`:

```sh
extsmaild: my_external: Received error 255 when executing '/usr/bin/ssh -q -C -l user example.net /usr/sbin/sendmail -t' on '/home/user/.extsmail/spool_dir/msgs/XXXXtj8lSB':
```
There is no message printed after the colon.

### PR DESCRIPTION
**Pull request by ltratt**
Should fix #37: confirmation welcome!

@oliv3: I've added you as a collaborator so if/when you're happy with this, hopefully you can merge it into master!

### CODE REVIEW

**Comment by ltratt** [comment]
Oops, I made a mistake in the first commit, which the second fixes. This will need squashing before merging. Mea culpa!

**Comment by oliv3** [comment]
It's somewhat fixed, but mails are still not sent.

**Comment by ltratt** [comment]
Mails are not sent? Is that with or without the second commit?

**Comment by oliv3** [comment]
I fetched the no_stderr_write branch so I have the latest two commits.

**Comment by oliv3** [comment]
I have absolutely no idea if this is the correct way of testing, but here's what I get when running sendmail on the remote host:

```sh
$ /usr/sbin/sendmail -t

v1
0
To: <olivier@biniou.info>
Subject: fdsfdsfds
X-Mailer: mail (GNU Mailutils 3.6)

fdsfsdfsd
2019-07-29 21:15:19 1hsB73-00027s-9e 1hsB73-00027s-9e no recipients found in headers
```

**Comment by ltratt** [comment]
I'm not sure that'll work, because it's not `sendmail`'s normal format. The way I try it is to do something like:

```sh
$ sendmail=/path/to/extsmail mail me@test.com
```

then type my message and (in classic `mail` fashion) just do `.` for the final line.

**Comment by oliv3** [comment]
I didn't change a single line, it was perfectly working before...

```sh
$ cat ~/.mailrc
set sendmail=/usr/bin/extsmail
$ ls ~/.extsmail/spool_dir/msgs
$ mail olivier@biniou.info
Cc: 
Subject: Test
test
^D
$ extsmaild -m batch
extsmaild: cthugha: Received error 255 when executing '/usr/bin/ssh -q -C -l olivier biniou.net /usr/sbin/sendmail -t' on '/home/olivier/.extsmail/spool_dir/msgs/XXXXbyJFZ5'
$ ls ~/.extsmail/spool_dir/msgs
XXXXbyJFZ5
```

**Comment by oliv3** [comment]
Found it, it was failing due to a SSH host key change :/

**Comment by ltratt** [comment]
Ah, that ideally needed squashing before merging. Not to worry though.

**Comment by oliv3** [comment]
They are squashed, aren't they ?

**Comment by ltratt** [comment]
Ideally they'd have been squashed down to one commit, since the second was just a bug fix to the first. It's not the end of the world.

**Comment by oliv3** [comment]
I may be missing something, but there's only one commit ?
https://github.com/ltratt/extsmail/commits/master

**Comment by ltratt** [comment]
Ah! I was expecting to squash it manually, but squashing it via GitHub works too. Sorry for the noise Olivier!

**Comment by oliv3** [comment]
No worry :) In this particular case, it would have been better to do a fixup rather than a squash in the no_stderr_write branch before merging though, so the second commit message would not be there.
I can fix that if really needed but that would mean a forced push in master ?

**Comment by ltratt** [comment]
I agree that a fixup would have been better, but I'd prefer to avoid forced pushes to master. It's not a big deal.

**Pull request merged**
