### PR TITLE
Prepare for a 2.3 release.

### PR DESCRIPTION
**Pull request by ltratt**

### CODE REVIEW

**Comment by ltratt** [comment]
Hmm, I'm not sure why those Travis checks are failing. Why does `yacc` generate code that doesn't type check?!

**Comment by oliv3** [comment]
I think it's a Travis issue.

**Comment by ltratt** [comment]
Trying to fix in #41 -- we should hold off thinking abot this PR until we're done over there.

**Comment by oliv3** [comment]
Do you want me to merge this one now ?

**Comment by ltratt** [comment]
No, please wait!

**Comment by ltratt** [comment]
OK, I've updated the history a bit in the new commit. If you're OK with this, I'll squash and force push for you to double check before merging and making a release.

**Comment by oliv3** [comment]
Sure, I'll build the Debian package which will double-check everything.

**Comment by ltratt** [comment]
OK, I've forced pushed so if/when you're happy, this is ready for merging.

**Comment by oliv3** [comment]
Looks good to me !

**Pull request merged**
