### PR TITLE
Keep sending messages even in the face of failure

### LINKED ISSUE #45: Empty file in the spool dir prevents extsmaild from sending mails
Hi Laurie,

I just ran into this issue: I was sending mails to my address but did not receive them.
A `ls -l ~/.extsmail/spool_dir/msgs/` showed an empty file and my mails.
Removing the empty file and restarting `extsmaild` solved the issue.

### PR DESCRIPTION
**Pull request by ltratt**
Before this PR, never-sendable messages could cause extsmaild to get stuck in the queue. This PR solves that issue, and also makes extsmaild try harder to send messages quickly in the face of failure. The basic idea is that as long as *some* messages are being sent successfully, we don't allow the failure to send other messages impose long delays. Only if the queue gets to the point where the remaining messages are all (currently) unsuccessful do we start to increment the sending delay.

Hopefully fixes #45 -- @oliv3, comments and testing are welcome! This is a fairly significant change, so I will be running this for quite a while before it goes into a new release.

### CODE REVIEW

**Comment by ltratt** [comment]
@oliv3 https://github.com/ltratt/extsmail/pull/48/commits/c587ac6bf0fad1ebdb1850ed6119eea5987603fe simplifies things heavily. If this works for you (and it works for me), I think we might be getting close to a good solution.

**Comment by ltratt** [comment]
@oliv3 I've been running with this patch for a few days and it seems to work well (better than the previous system) even with "bad" files clogging up the queue. Have you had a chance to try it?

**Comment by oliv3** [comment]
Not yet, I'm pretty busy until at least next week. Will let you know !

**Comment by oliv3** [comment]
Hi, I just fetched the branch and got this error:
```
gcc -g -O2 -std=c99 -Wall -pedantic -Wextra -D_POSIX_C_SOURCE=2   -c -o extsmaild.o extsmaild.c
extsmaild.c: In function ‘cycle’:
extsmaild.c:411:29: warning: implicit declaration of function ‘arc4random_uniform’ [-Wimplicit-function-declaration]
  411 |             uint32_t skip = arc4random_uniform(num_entries);
      |                             ^~~~~~~~~~~~~~~~~~
```

**Comment by ltratt** [comment]
It looks like `arc4random_uniform` is typically part of libbsd under linux? If there's a portable alternative to `arc4random_uniform`, or if you have suggestions for how to test for this in `configure.ac`, I'm all ears!

**Comment by oliv3** [comment]
It is available on Linux, but you would need to `#include <bsd/stdlib.h>` and link with `-lbsd`.

**Comment by oliv3** [comment]
```
$ pkg-config libbsd --libs
-lbsd
```

**Comment by ltratt** [comment]
I assume we'd need to test for that in `configure.ac`? Is there a portable alternative to `arc4random_uniform`? The precise random function we use isn't *too* important.

**Comment by oliv3** [comment]
From the man page:
```
DESCRIPTION
     This family of functions provides higher quality data than those described in rand(3), random(3), and rand48(3).
```

Do you really want a cryptographically-secure random here ? I'd go with a good ol' random function `% num_entries` :)

**Comment by ltratt** [comment]
Hopefully https://github.com/ltratt/extsmail/pull/48/commits/3497cae7113477c24bd005c41f1839440a6bf98a should work (I've checked it compiles on a Linux box, but I haven't checked if it runs properly!).

**Comment by oliv3** [comment]
So I made this test: I created 100 empty files in the spool dir, then sent 4 mails. After some time 3 went through, but one was stuck.

Then I sent another 2 mails, it took some time but I received 1. After some minutes another one, and after some other minutes the last one.

I sent a final one, which I received 10 minutes after.

So it looks like it's working, but the mails don't get sent immediately as it was in the past ?

**Comment by ltratt** [comment]
The timing behaviour does seem a bit odd and unexpected. Do you happen to have the output from the maillog with send successes/failures?

**Comment by oliv3** [comment]
I replied by mail but it seems it didn't make it here, which maillog output ?

**Comment by ltratt** [comment]
Basically wherever extsmaild is logging message sends e.g.:

```
Jul 10 11:07:07 overdrive extsmaild: XYZ: Message '/home/ltratt/.extsmail/spool_dir/msgs/zsH4S3Nu3o' sent
```

that would also tell us if there are failures in there (which might explain the delay you're seeing).

**Comment by oliv3** [comment]
Oh - `/var/log/mail.log` only talks about sent messages, I see no errros here.

**Comment by ltratt** [comment]
Can you try this diff and see if it solves the weird delay?

```
diff --git extsmaild.c extsmaild.c
index 0ba15d1..661fe6c 100644
--- extsmaild.c
+++ extsmaild.c
@@ -444,10 +444,8 @@ static int cycle(Conf *conf, Group *groups, Status *status)
             if (errno == 0) {
                 // We've got to the end of the directory.
                 if (conf->mode == DAEMON_MODE) {
-                    if (reached_end
-                      || (!reached_end && !status->any_failure && num_successes == 0)) {
+                    if (reached_end)
                         break;
-                    }
                     reached_end = true;
                     rewinddir(dirp);
                     continue;
```

**Comment by oliv3** [comment]
I sent 5 mails at 18:26, and here's the relevant log:
```
Jul 11 18:27:34 adoy extsmaild: cthugha: Message '/home/olivier/.extsmail/spool_dir/msgs/XXXXNnhiFO' sent
Jul 11 18:29:04 adoy extsmaild: cthugha: Message '/home/olivier/.extsmail/spool_dir/msgs/XXXXW7l283' sent
Jul 11 18:29:23 adoy extsmaild: cthugha: Message '/home/olivier/.extsmail/spool_dir/msgs/XXXXL6qp69' sent
Jul 11 18:29:53 adoy extsmaild: cthugha: Message '/home/olivier/.extsmail/spool_dir/msgs/XXXXYen15k' sent
Jul 11 18:32:57 adoy extsmaild: cthugha: Message '/home/olivier/.extsmail/spool_dir/msgs/XXXXIbVajA' sent
```
So I received all of them, but with some delay (see the timestamps).

**Comment by oliv3** [comment]
I'll try your patch.

**Comment by oliv3** [comment]
I sent a batch of 20 messages at 18:43:
```
Jul 11 18:49:39 adoy extsmaild: cthugha: Message '/home/olivier/.extsmail/spool_dir/msgs/XXXXF9EH3m' sent
Jul 11 18:49:54 adoy extsmaild: cthugha: Message '/home/olivier/.extsmail/spool_dir/msgs/XXXXsU4HfH' sent
Jul 11 18:49:55 adoy extsmaild: cthugha: Message '/home/olivier/.extsmail/spool_dir/msgs/XXXXFUAO0C' sent
Jul 11 18:49:58 adoy extsmaild: cthugha: Message '/home/olivier/.extsmail/spool_dir/msgs/XXXX3dHWdF' sent
Jul 11 18:50:02 adoy extsmaild: cthugha: Message '/home/olivier/.extsmail/spool_dir/msgs/XXXXWTy6UW' sent
Jul 11 18:50:02 adoy extsmaild: cthugha: Message '/home/olivier/.extsmail/spool_dir/msgs/XXXX9fCkSq' sent
Jul 11 18:50:09 adoy extsmaild: cthugha: Message '/home/olivier/.extsmail/spool_dir/msgs/XXXXI4FWxZ' sent
Jul 11 18:50:09 adoy extsmaild: cthugha: Message '/home/olivier/.extsmail/spool_dir/msgs/XXXXk0lpHe' sent
Jul 11 18:50:52 adoy extsmaild: cthugha: Message '/home/olivier/.extsmail/spool_dir/msgs/XXXXKCZeS5' sent
Jul 11 18:51:10 adoy extsmaild: cthugha: Message '/home/olivier/.extsmail/spool_dir/msgs/XXXXgyLN5r' sent
Jul 11 18:51:23 adoy extsmaild: cthugha: Message '/home/olivier/.extsmail/spool_dir/msgs/XXXXRci8S1' sent
Jul 11 18:52:09 adoy extsmaild: cthugha: Message '/home/olivier/.extsmail/spool_dir/msgs/XXXXSAPzOB' sent
Jul 11 18:52:24 adoy extsmaild: cthugha: Message '/home/olivier/.extsmail/spool_dir/msgs/XXXXjfdAPY' sent
Jul 11 18:52:28 adoy extsmaild: cthugha: Message '/home/olivier/.extsmail/spool_dir/msgs/XXXXxczAMy' sent
Jul 11 18:52:40 adoy extsmaild: cthugha: Message '/home/olivier/.extsmail/spool_dir/msgs/XXXXA2HH5R' sent
Jul 11 18:52:50 adoy extsmaild: cthugha: Message '/home/olivier/.extsmail/spool_dir/msgs/XXXXKrghhf' sent
Jul 11 18:52:53 adoy extsmaild: cthugha: Message '/home/olivier/.extsmail/spool_dir/msgs/XXXXnkcIRw' sent
Jul 11 18:52:54 adoy extsmaild: cthugha: Message '/home/olivier/.extsmail/spool_dir/msgs/XXXXHzCxJh' sent
Jul 11 18:53:03 adoy extsmaild: cthugha: Message '/home/olivier/.extsmail/spool_dir/msgs/XXXXByLJYo' sent
Jul 11 18:53:04 adoy extsmaild: cthugha: Message '/home/olivier/.extsmail/spool_dir/msgs/XXXXTEhuau' sent
```

**Comment by oliv3** [comment]
So roughly 2 mails/min.

**Comment by ltratt** [comment]
Were you adding new messages to the queue while extsmaild was sending, or was the queue full, you ran extsmaild, and then it was sending ~2 mails/min until the queue was fully sent (excluding empty messages)?

**Comment by oliv3** [comment]
It was running.

**Comment by ltratt** [comment]
Does that mean 2 msgs/min was the rate you were injecting them, or it should have been sending more? [Sorry to be a pain: I'm trying to visualise the details of the problem you're seeing!]

**Comment by oliv3** [comment]
I did that:
```
$ time for i in `seq 1 20`; do echo `date` | mail -s "Mail $i" olivier@biniou.info; done

real    0m0.393s
user    0m0.269s
sys     0m0.182s
```

**Comment by oliv3** [comment]
They were *sent* at a rate of 2/min.

**Comment by ltratt** [comment]
Aha, I think I now see the basic problem. https://github.com/ltratt/extsmail/pull/48/commits/3c8da592cace57307831846f27d65e4df9c02173 simplifies more things. If you send N messages in one go, it's possible it will take two goes through the queue (separated by a minute) to send them all (long story) -- but, in theory, you should now see all the messages sent more promptly than before.

**Comment by oliv3** [comment]
It is much better now ! Extsmaild was running, sent a batch of 20 mails, they *all* got sent in the following seconds in one go.

**Comment by ltratt** [comment]
Excellent! I do have some further ideas for further cleanup, but I think this is enough simplification and change for one PR :) Can we both run this for 1 week and report back on whether we find any issues with these changes or not? If we don't... I think we have a winner!

**Comment by oliv3** [comment]
Sure ! Good job :)

**Comment by ltratt** [comment]
@oliv3 How have you got on with testing this? It's working fine for me.

**Comment by oliv3** [comment]
I've been trying hard to break it without luck, looks pretty stable now.

**Comment by ltratt** [comment]
Thanks @oliv3!

**Comment by ltratt** [comment]
BTW, since you're the reviewer, I think you should press the "merge" button :) I will return the favour with #49 once this PR is merged!

**Pull request merged**
