### PR TITLE
Fix build dependencies.

### PR DESCRIPTION
**Pull request by oliv3**

### CODE REVIEW

**Comment by ltratt** [comment]
I'm nervous about hard-coding the dependencies in: if we change them, we'll probably forget to update things, and then confusion will result. We could, perhaps, have a "make dependencies" target, and ship the result of that in the tarball so that it's always up to date?

**Comment by oliv3** [comment]
Or, make it compliant with the autotools build chain ?

**Comment by ltratt** [comment]
What would that entail?

**Comment by oliv3** [comment]
Not too much, let me give this a try.

**Pull request closed without merging**
