### PR TITLE
Add debian/ directory.

### PR DESCRIPTION
**Pull request by oliv3**
This directory is not meant to be shipped in the official tarballs, but needed for 2.2 to reach the next Debian release.

### CODE REVIEW

**Comment by ltratt** [comment]
I don't understand why we need this in the extsmail repository: surely this should be version controlled within Debian? The idea of having the zillions of Linux distros storing their details in the repository fills me with dread!

**Comment by oliv3** [comment]
It doesn't have to be in master, a "debian" branch would be enough.

**Comment by ltratt** [comment]
Does it have to be in this repo? Or can we have a separate extsmail_debian repo (or similar)?

**Comment by oliv3** [comment]
There actually is one: https://github.com/oliv3/extsmail-debian.

Problem is that it only contains the debian/ directory, not the sources. And, debian/control has `Vcs-Browser: https://github.com/ltratt/extsmail` (_mea maxima culpa_, thought it should point to upstream as informational, but it's not -see [here](https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-vcs-fields)-).

Unfortunately, due to the freeze, this can't be fixed right now. So there are two options here:
* temporarily add this directory here, it can/will be removed after the freeze, for e.g. extsmail-2.3
* extsmail goes out of Debian (2.0 was removed from testing)

Tried my best to get 2.2 in, but you're the boss...

**Comment by ltratt** [comment]
OK, I understand. If it's temporary, I can live with it. Just to check: this can go in a debian branch that, at some point, we delete so that it wouldn't even appear to be part of master's history?

**Comment by oliv3** [comment]
I think so.

**Comment by ltratt** [comment]
OK, I've pushed this into a "debian" branch. If that works for you, I guess you can then close this pull request?

**Comment by oliv3** [comment]
Sure, next time/release, I'll change the Vcs-* fields to point to my github fork. 
This will also save me from having a separate repository.

**Comment by oliv3** [comment]
This branch may safely be deleted now (cf [bug #924027](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=924027)).

**Comment by ltratt** [comment]
Thanks Olivier -- I've deleted the branch!

**Pull request closed without merging**
